import { assertEquals, assertNotEquals } from "std/assert";

// ---------------------------------------------------------------------------
// Security Suite: Sensitive Data Leak & Payload Compliance
// ---------------------------------------------------------------------------

Deno.test("Security Compliance - Zero Sensitive Key & Credential Leaks in Payloads", async (t) => {
  const MOCK_SERVICE_ROLE_KEY = "mock_supabase_service_role_key_value_not_leaked";
  const MOCK_STRIPE_SECRET_KEY = "mock_stripe_secret_key_value_not_leaked";
  const MOCK_WEBHOOK_SECRET = "mock_stripe_webhook_secret_value_not_leaked";

  // Simulate various API response objects generated by Edge Functions
  const mockApiResponses = [
    {
      status: 200,
      body: JSON.stringify({
        success: true,
        user: { id: "usr_123", name: "Jane Doe", email: "jane@cloudvault.com" },
        facility: { id: "facility_seattle_north", name: "Seattle North" },
        invoice: { id: "inv_123", total: 50.00, status: "paid" },
      }),
    },
    {
      status: 400,
      body: JSON.stringify({
        error: "Invalid request payload: Missing toteCount.",
      }),
    },
    {
      status: 500,
      body: JSON.stringify({
        error: "Handler execution error: An internal error occurred.",
      }),
    },
  ];

  await t.step("ensures responses never leak Supabase service role or Stripe secret keys", () => {
    for (const res of mockApiResponses) {
      assertEquals(res.body.includes(MOCK_SERVICE_ROLE_KEY), false, "Leaked SUPABASE_SERVICE_ROLE_KEY in response body!");
      assertEquals(res.body.includes(MOCK_STRIPE_SECRET_KEY), false, "Leaked STRIPE_SECRET_KEY in response body!");
      assertEquals(res.body.includes(MOCK_WEBHOOK_SECRET), false, "Leaked STRIPE_WEBHOOK_SECRET in response body!");
    }
  });

  await t.step("ensures internal database stack traces are sanitized from client error responses", () => {
    const rawDbError = new Error("Postgres query failed: select * from auth.users where password_hash = '$2b$12$rawHash' in /var/db/internal.ts:42");
    
    // Standard sanitize function used across CloudVault edge functions
    function sanitizeErrorMessage(err: Error): string {
      if (err.message.includes("Postgres") || err.message.includes("password_hash") || err.message.includes("auth.users")) {
        return "Database operation failed. Request could not be completed.";
      }
      return err.message;
    }

    const sanitized = sanitizeErrorMessage(rawDbError);
    assertEquals(sanitized.includes("password_hash"), false, "Error message contains raw password hash or internal query details!");
    assertEquals(sanitized.includes("auth.users"), false, "Error message contains internal table details!");
    assertEquals(sanitized, "Database operation failed. Request could not be completed.");
  });

  await t.step("ensures employee badge tokens are SHA-256 hashed before database transmission", async () => {
    const rawBadgeToken = "CV-AUTH-A98B2C3D4E";

    // Hash algorithm used in supabase-config.js hashBadgeToken
    async function hashBadgeToken(token: string): Promise<string> {
      const cleanToken = token.trim();
      const encoder = new TextEncoder();
      const data = encoder.encode(cleanToken);
      const hashBuffer = await crypto.subtle.digest("SHA-256", data);
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
    }

    const tokenHash = await hashBadgeToken(rawBadgeToken);

    // Assert hash is a 64-character lowercase hex string
    assertEquals(tokenHash.length, 64);
    assertEquals(/^[0-9a-f]{64}$/.test(tokenHash), true);

    // Assert the RPC payload sends the hash, never the raw token string
    const rpcPayload = { p_token_hash: tokenHash };
    assertEquals(JSON.stringify(rpcPayload).includes(rawBadgeToken), false, "Raw badge token leaked into RPC payload!");
    assertEquals(rpcPayload.p_token_hash, tokenHash);
  });
});